import {
  Calendar,
  Camera,
  Video,
  Mic,
  Music,
  Music2,
  Volume2,
  Square,
  Flower,
  Utensils,
  Palette,
  Hammer,
  Droplets,
  Zap,
  Paintbrush,
  Home,
  Triangle,
  DoorOpen,
  Building,
  Thermometer,
  Trees,
  Layout,
  Laptop,
  Code,
  Smartphone,
  Monitor,
  Share2,
  Search,
  PenTool,
  Film,
  Wrench,
  SprayCan,
  Baby,
  Heart,
  Car,
  Settings,
  Briefcase,
  Scale,
  Calculator,
  TrendingUp,
  Target,
  Users,
} from "lucide-react-native";

// Mapping of icon names to actual Lucide icon components
export const ICON_MAPPING = {
  calendar: Calendar,
  camera: Camera,
  video: Video,
  mic: Mic,
  music: Music,
  "music-2": Music2,
  "volume-2": Volume2,
  square: Square,
  flower: Flower,
  utensils: Utensils,
  palette: Palette,
  hammer: Hammer,
  droplets: Droplets,
  zap: Zap,
  paintbrush: Paintbrush,
  home: Home,
  triangle: Triangle,
  "door-open": DoorOpen,
  building: Building,
  thermometer: Thermometer,
  trees: Trees,
  layout: Layout,
  laptop: Laptop,
  code: Code,
  smartphone: Smartphone,
  monitor: Monitor,
  "share-2": Share2,
  search: Search,
  "pen-tool": PenTool,
  film: Film,
  wrench: Wrench,
  "spray-can": SprayCan,
  baby: Baby,
  heart: Heart,
  car: Car,
  settings: Settings,
  briefcase: Briefcase,
  scale: Scale,
  calculator: Calculator,
  "trending-up": TrendingUp,
  target: Target,
  users: Users,
};

// Helper function to get icon component by name
export const getIconComponent = (iconName) => {
  return ICON_MAPPING[iconName] || Wrench; // Default to Wrench if icon not found
};
